# Site settings
name: "부규필"
email: "qfeel0812@gmail.com"
url: "https://Qfeel-Dev.com"
description: "A blog and a portfolio"
author: "author"
title: "BlogFolio"
permalink: pretty
baseurl: "https://qfeel-dev.github.io/"

# social
github:
  username: Qfeel-Dev

twitter:
  username: Qfeel-Dev
